### ISSUE TITLE
Packages available in local cache repository are downloaded again

### ISSUE THREAD

**Issue by jsullivan3** [jsullivan3/dnf-local-cache-actions#3]
As reported by @gjohnz in https://github.com/rpm-software-management/dnf5/issues/926:

Packages are being downloaded again rather than referenced from the local cache repository.

**Comment by jsullivan3** [comment]
I see a problem on `x86_64` when `archdirs = true` such that `i686` architecture RPMs are correctly saved to the local cache, but because the the repositories are defined for only `noarch` and the architecture of the system, in this case `x86_64`, DNF never reads from the `i686` repository to make use of the local cache.  Darn.

Unfortunately, the repository metadata isn't being created for that local cache repository either.

And I confirmed that without the architecture-specific repository enabled, the repo metadata isn't being updated.  That behavior should be relatively straightforward to fix though.  Unfortunately I do not have a workaround for it...

**Comment by jsullivan3** [comment]
I verified the fixes, I think, and this issue should be addressed in version 0.2 which I hope to release sometime this evening or tomorrow.  Thanks again, @gjohnz!

**Comment by gjohnz** [comment]
I jut installed Fedora 41 Workstation today and it seems that your software is working properly. The local repository is being read from and used, newly downloaded files appear to get added to the repository. Any issues previously reported were experienced while running Cinnamon 41 or LXDE 41, for the record.

**Comment by jsullivan3** [comment]
Excellent - thank you very much for your feedback, @gjohnz!  I'm happy to hear it's working well for you.

**Comment by dioni21** [comment]
Sorry for the necrocomment, but should dnf reinstall use local repo or not?
